# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Samanvitha
tagline:          'Molecular Dynamics'
description:      'Personal website of Samanvitha — research, projects, publications, and resources.'
url:              https://samanvithavs.github.io
baseurl:          ""

author:
  name:           'Samanvitha'
  url:            https://samanvithavs.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/Samanvithavs/samanvithavs.github.io
